import React, { ReactNode } from 'react';
import { notFound } from 'next/navigation';
import { Metadata } from 'next';
import 'primereact/resources/themes/lara-light-cyan/theme.css';
import { NextIntlClientProvider } from 'next-intl';

import '@style';
import { Footer, Header } from '@components';

export const metadata: Metadata = {
  title: 'Pet your Pet ',
  description: 'Generated by create next app',
};
type Props = {
  children: ReactNode;
  params: { locale: string; path?: string };
};
export default async function RootLayout(props: Props) {
  const { params, children } = props;

  let messages;
  try {
    messages = (await import(`../../../messages/${params.locale}.json`)).default;
  } catch (error) {}

  if (!messages) return notFound();
  return (
    <html
      lang={params.locale}
      dir={params.locale === 'en' ? 'ltr' : 'rtl'}
      data-layout-dir={params.locale === 'en' ? 'ltr' : 'rtl'}
      data-preloader="disable"
    >
      <body dir={params.locale === 'en' ? 'ltr' : 'rtl'}>
        <NextIntlClientProvider locale={params.locale} messages={messages}>
          <header>
            <Header />
          </header>
          <main className="min-vh-100">{children}</main>
          <footer className="mt-5">
            <Footer />
          </footer>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
